### ISSUE TITLE
API document

### ISSUE THREAD

**Issue by Schaussi** [stevestokes/focustronic-datacollector#1]
Hello,

thank you for this project, looks very interesting.
Do you maybe have resources like a Focustronic (especially Mastertronic) API documentation which you could share?
In my case I would like to implement an integration for Home Assistant to be able to get the recent measurement values.

(Direct access to a local API of the device would be even better, though I'm afraid it would not be possible.)

Thank you,
best regards

**Comment by stevestokes** [comment]
Their API is not public, but also not hidden. You will need to sniff traffic in order to get all API endpoints - note, this project does pull current MT measurement values, and this is done through direct local API access. This project encapsulates all of that, check it out a bit deeper and you'll find all you're looking for :)

**Comment by Schaussi** [comment]
Sounds great, thank you :)
